spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentDB
    username: postgres
    password: qwer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9191